name: Publish Package
on:
  push:
    branches:
      - "main"
    paths:
      - "app/**"
      - ".github/workflows/publish.yml"
permissions:
  id-token: write
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install setuptools wheel twine
      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel
 
      - name: List Directory Content
        run: |
           pwd
      - name: List Directory Content
        run: |
           ls
      - name: List Dist Directory Content
        run: |
           ls -R dist
      - name: Upload release asset to GitHub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://github.com/NAIKP19/Vessel-Services-Package-Test/releases/latest/assets
          asset_path: dist/test_vessel_services-0.1.0-py3-none-any.whl
          asset_name: app-package.whl
          asset_content_type: application/octet-stream
