name: Publish Package
 
on:
  push:
    branches:
      - "main"
    paths:
      - "app/**"
      - ".github/workflows/publish.yml"
 
permissions:
  id-token: write
  contents: write
 
jobs:
  publish:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
 
      - name: Install dependencies
        run: |
          pip install setuptools wheel twine
 
      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: List Directory Content
        run: |
           pwd
           
      - name: List Directory Content
        run: |
           ls
           
      - name: List Dist Directory Content
        run: |
           ls -R dist
           
      - name: Install GitHub CLI # New step added
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          
      - name: Authenticate GitHub CLI # New step added
        env:
          GH_TOKEN: ${{ secrets..GITHUB_TOKEN }}
        run: |
          echo $GH_TOKEN | gh auth login --with-token
          
      - name: Upload release asset to GitHub # New step added
        env:
          GH_TOKEN: ${{ secrets..GITHUB_TOKEN }}
        run: |
          gh release upload latest dist/*.whl --repo https://github.com/NAIKP19/Vessel-Services-Package-Test
